import React,{useEffect,useState} from 'react'
import {api} from './api'
type View='overview'|'appointments'|'patients'|'profile'
type Doctor=Record<string,any>
const arr=(x:any)=>Array.isArray(x)?x:Array.isArray(x?.data)?x.data:Array.isArray(x?.data?.items)?x.data.items:Array.isArray(x?.items)?x.items:[]
function Login({done}:{done:(d:any,t:string)=>void}){
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 async function submit(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);try{const r:any=await api.login(email,password);const t=r.access_token||r.data?.accessToken;if(!t)throw Error(r.message||'Access token missing');const d=r.data?.doctor||r.data?.user||r.data||{};localStorage.setItem('doctor_access_token',t);localStorage.setItem('doctor_user',JSON.stringify(d));done(d,t)}catch(e:any){setError(e.message||'Unable to login')}finally{setBusy(false)}}
 return <div className="auth"><div className="authcard"><div className="brand">VANDYCINS</div><h1>Doctor Portal</h1><p>Sign in to manage appointments and patients.</p>{error&&<div className="alert error">{error}</div>}<form onSubmit={submit}><label>Email</label><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="doctor@example.com"/><label>Password</label><input type="password" required value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••"/><button className="primary full" disabled={busy}>{busy?'Signing In...':'Sign In'}</button></form><small>Only approved and active doctors can access the portal.</small></div></div>
}
function App(){
 const [doctor,setDoctor]=useState<Doctor|null>(()=>{try{return JSON.parse(localStorage.getItem('doctor_user')||'null')}catch{return null}})
 const [view,setView]=useState<View>('overview'),[appointments,setAppointments]=useState<any[]>([]),[patients,setPatients]=useState<any[]>([]),[profile,setProfile]=useState<Doctor>(doctor||{}),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false)
 const logged=!!doctor&&!!localStorage.getItem('doctor_access_token')
 useEffect(()=>{if(logged)load()},[logged])
 async function load(){setLoading(true);setNotice('');const rs=await Promise.allSettled([api.profile(),api.appointments(),api.patients()]);if(rs[0].status==='fulfilled'){const p=rs[0].value.data?.doctor||rs[0].value.data||{};setProfile(p);setDoctor(p);localStorage.setItem('doctor_user',JSON.stringify(p))}if(rs[1].status==='fulfilled')setAppointments(arr(rs[1].value));if(rs[2].status==='fulfilled')setPatients(arr(rs[2].value));if(rs.every(x=>x.status==='rejected'))setNotice('API is not reachable. Check VITE_API_BASE_URL and backend routes.');setLoading(false)}
 function logout(){localStorage.removeItem('doctor_access_token');localStorage.removeItem('doctor_user');setDoctor(null)}
 async function status(id:string,s:string){try{await api.appointmentStatus(id,s);setNotice(`Appointment ${s.toLowerCase()}.`);load()}catch(e:any){setNotice(e.message||'Unable to update appointment.')}}
 if(!logged)return <Login done={(d)=>{setDoctor(d);setProfile(d)}}/>
 const active=appointments.filter(a=>!['COMPLETED','CANCELLED'].includes(String(a.status||'').toUpperCase())).length
 const completed=appointments.filter(a=>String(a.status||'').toUpperCase()==='COMPLETED').length
 return <div className="shell"><aside><div className="brand">VANDYCINS</div><small>Doctor Portal</small><nav><button className={view==='overview'?'active':''} onClick={()=>setView('overview')}>Overview</button><button className={view==='appointments'?'active':''} onClick={()=>setView('appointments')}>Appointments</button><button className={view==='patients'?'active':''} onClick={()=>setView('patients')}>Patients</button><button className={view==='profile'?'active':''} onClick={()=>setView('profile')}>My Profile</button></nav><button className="logout" onClick={logout}>Sign Out</button></aside><main><header><div><h2>{view==='overview'?'Overview':view[0].toUpperCase()+view.slice(1)}</h2><span>Doctor workspace</span></div><div className="user"><b>{profile.name||doctor?.name||'Doctor'}</b><small>{profile.specialization||'Doctor'}</small></div></header>{notice&&<div className="alert info">{notice}</div>}{view==='overview'&&<><section className="welcome"><div><em>WELCOME BACK</em><h1>Dr. {profile.name||'Doctor'}</h1><p>{profile.specialization||'Medical professional'} · {profile.qualification||'Qualification not available'}</p></div><button onClick={load}>{loading?'Refreshing...':'Refresh Data'}</button></section><section className="stats"><Stat t="Appointments" v={appointments.length}/><Stat t="Active" v={active}/><Stat t="Completed" v={completed}/><Stat t="Patients" v={patients.length}/></section><Panel title="Upcoming Appointments" action={()=>setView('appointments')}><Appointments rows={appointments.slice(0,5)} change={status}/></Panel></>}{view==='appointments'&&<Panel title="Appointments"><Appointments rows={appointments} change={status}/></Panel>}{view==='patients'&&<Panel title="Patients">{patients.length?<table><thead><tr><th>Patient</th><th>Email</th><th>Mobile</th><th>Status</th></tr></thead><tbody>{patients.map((p,i)=><tr key={p.id||i}><td>{p.name||p.patientName||'—'}</td><td>{p.email||'—'}</td><td>{p.mobile||p.phone||'—'}</td><td>{p.status||'ACTIVE'}</td></tr>)}</tbody></table>:<Empty/>}</Panel>}{view==='profile'&&<Profile p={profile} saved={p=>{setProfile(p);setDoctor(p);localStorage.setItem('doctor_user',JSON.stringify(p))}}/>}</main></div>
}
function Stat({t,v}:{t:string,v:number}){return <div className="stat"><span>{t}</span><b>{v}</b></div>}
function Panel({title,children,action}:{title:string,children:React.ReactNode,action?:()=>void}){return <section className="panel"><div className="panelhead"><h3>{title}</h3>{action&&<button className="link" onClick={action}>View all</button>}</div>{children}</section>}
function Appointments({rows,change}:{rows:any[],change:(id:string,s:string)=>void}){if(!rows.length)return <Empty/>;return <div className="table"><table><thead><tr><th>Patient</th><th>Date</th><th>Time</th><th>Type</th><th>Status</th><th>Action</th></tr></thead><tbody>{rows.map((a,i)=>{const id=String(a.id||'');const s=String(a.status||'PENDING').toUpperCase();return <tr key={id||i}><td>{a.patientName||a.patient?.name||'—'}</td><td>{a.date||'—'}</td><td>{a.time||'—'}</td><td>{a.type||'Consultation'}</td><td><span className="badge">{s}</span></td><td>{id&&!['COMPLETED','CANCELLED'].includes(s)?<><button className="mini" onClick={()=>change(id,'CONFIRMED')}>Confirm</button><button className="mini" onClick={()=>change(id,'COMPLETED')}>Complete</button></>:'—'}</td></tr>})}</tbody></table></div>}
function Profile({p,saved}:{p:Doctor,saved:(p:any)=>void}){const [f,setF]=useState(p),[msg,setMsg]=useState('');const set=(k:string,v:any)=>setF({...f,[k]:v});async function save(e:React.FormEvent){e.preventDefault();try{const r:any=await api.updateProfile(f);saved(r.data?.doctor||r.data||f);setMsg('Profile updated successfully.')}catch(e:any){setMsg(e.message||'Unable to update profile.')}}return <section className="panel"><div className="panelhead"><h3>My Profile</h3></div>{msg&&<div className="alert info">{msg}</div>}<form className="grid" onSubmit={save}>{[['name','Full Name'],['email','Email'],['mobile','Mobile'],['specialization','Specialization'],['qualification','Qualification'],['registrationNumber','Registration Number'],['clinicName','Clinic Name'],['clinicAddress','Clinic Address']].map(([k,l])=><div><label>{l}</label><input value={f[k]||''} onChange={e=>set(k,e.target.value)}/></div>)}<div className="wide"><label>Bio</label><textarea rows={4} value={f.bio||''} onChange={e=>set('bio',e.target.value)}/></div><div className="wide"><button className="primary">Save Changes</button></div></form></section>}
function Empty(){return <div className="empty">No data returned by the API.</div>}
export default App